name: Build
on: [push]

jobs:
  build:
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - name: Compile
        run: sbt +compile
